
from typing import Union, List, Type
import numbers

ValidVector = Union['Vector', numbers.Real]

class Vector2:

    __slots__ = ("x", "y")

    x: numbers.Real
    y: numbers.Real

    def __init__(self, x: numbers.Real, y: numbers.Real = ...) -> None: ...

    def __repr__(self) -> str: ...

    def flatten(self) -> float: ...

    def to_3d(self) -> Vector: ...

class Vector3:

    __slots__ = ("x", "y", "z")

    x: numbers.Real
    y: numbers.Real
    z: numbers.Real

    def __init__(self, x: numbers.Real, y: numbers.Real = ..., z: numbers.Real = ...) -> None: ...

    def __repr__(self) -> str: ...

    def __int__(self) -> None: ...

    def __float__(self) -> float: ...

    def __add__(self, other: ValidVector) -> Vector: ...

    def __sub__(self, other: ValidVector) -> Vector: ...

    def __mul__(self, other: ValidVector) -> Vector: ...

    def __rmul__(self, other: ValidVector) -> Vector: ...

    def __matmul__(self, other: Vector) -> Vector: ...

    def __truediv__(self, other: ValidVector) -> Vector: ...

    def __floordiv__(self, other: ValidVector) -> Vector: ...

    def __neg__(self) -> Vector: ...

    def __abs__(self) -> float: ...

    def __round__(self, n: int = ...) -> Vector: ...

    def __trunc__(self) -> Vector: ...

    def __floor__(self) -> Vector: ...

    def __ceil__(self) -> Vector: ...

    def flatten(self) -> float: ...

    def cross(self, other: Vector) -> Vector: ...

    def to_2d(self) -> Vector2: ...

Vector: Type[Vector3] = Vector3

def rect_list(top_left: Vector, bottom_right: Vector) -> List[Vector]: ...

UnitX: Vector
UnitY: Vector
UnitZ: Vector
