
from PIL.Image import Image
from spidertools.common.parsers import ArgParser
from minecraft.schematic import Schematic

BASE_COLOR: str = ...
BORDER_COLOR: str = ...
HELP_MESSAGE: str = ...

LINE_SIZE: int = ...
IMAGE_BOUNDARY: int = ...
LAYER_BOUNDARY: int = ...

def get_texture(x: int, y: int, z: int) -> Image: ...

def draw_grid(img: Image) -> None: ...

def generate_grid() -> Image: ...

def generate_blueprint() -> Image: ...

def generate_key() -> Image: ...

def generate_count() -> Image: ...

def create_image(parser: ArgParser) -> Image: ...

def setup_globals(parser: ArgParser) -> None: ...

def main() -> int: ...
