
from typing import Optional
from pathlib import Path
from PIL.Image import Image
from utils.argparser import ArgParser
from minecraft.schematic import Schematic

DEFAULT_RESOURCE_DIR: Path = ...
DEFAULT_LINE_SIZE: int = ...

BASE_COLOR: str = ...
BORDER_COLOR: str = ...
HELP_MESSAGE: str = ...

IMAGE_BOUNDARY: int = ...
LAYER_BOUNDARY: int = ...
BLOCK_SIZE: int = ...
EF_SIZE: int = ...

LINE_SIZE: type(DEFAULT_LINE_SIZE) = ...

def get_texture(namespace: str, block: str, data: int) -> Image: ...

def draw_grid(img: Image) -> None: ...

def generate_base(schematic: Schematic) -> Image: ...

def create_image(schematic: Schematic, parser: ArgParser) -> Image: ...

def place_blocks(img: Image, schematic: Schematic) -> None: ...

def generate_key(schematic: Schematic) -> Image: ...

def generate_count(schematic: Schematic) -> Image: ...

def load_schematic(parser: ArgParser) -> Optional[Schematic]: ...

def main() -> int: ...
