
from PIL.Image import Image
from utils.argparser import ArgParser
from minecraft.schematic import Schematic

BASE_COLOR: str = ...
BORDER_COLOR: str = ...
HELP_MESSAGE: str = ...

LINE_SIZE: int = ...
IMAGE_BOUNDARY: int = ...
LAYER_BOUNDARY: int = ...

def get_texture(namespace: str, block: str, data: int) -> Image: ...

def draw_grid(img: Image) -> None: ...

def generate_grid(schematic: Schematic) -> Image: ...

def generate_blueprint(schematic: Schematic) -> None: ...

def generate_key(schematic: Schematic) -> Image: ...

def generate_count(schematic: Schematic) -> Image: ...

def create_image(schematic: Schematic, parser: ArgParser) -> Image: ...

def setup_globals(parser: ArgParser) -> None: ...

def main() -> int: ...
